### ISSUE TITLE
openUrlConnection: \\n Opening url https:\/\/foo.bar.org\/mail\/ failed with Encountered end of file

### ISSUE THREAD

**Issue by yeoldegrove** [hypery2k/owncloud#353]
The following error messages are seen in owcloud.log after saving settings in the roundcube app:

```
{"reqId":"VhdqwYAkdBbFF2CKNBDQuwAAAAA","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: password at \/var\/www\/html\/owncloud\/apps\/roundcube\/lib\/RoundCubeAuthHelper.class.php#55","level":3,"time":"2015-10-09T07:20:33+00:00"}
{"reqId":"VhdqwYAkdBbFF2CKNBDQuwAAAAA","remoteAddr":"127.0.0.1","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Opening url https:\/\/foo.bar.org\/mail\/ failed with Encountered end of file","level":3,"time":"2015-10-09T07:20:34+00:00"}
{"reqId":"VhdqwYAkdBbFF2CKNBDQuwAAAAA","remoteAddr":"127.0.0.1","app":"roundcube","message":"RoundcubeLogin.class.php: openUrlConnection: \\n Opening url https:\/\/foo.bar.org\/mail\/ failed with Encountered end of file","level":3,"time":"2015-10-09T07:20:34+00:00"}
{"reqId":"VhdqwYAkdBbFF2CKNBDQuwAAAAA","remoteAddr":"127.0.0.1","app":"roundcube","message":"OC_RoundCube_AuthHelper.class.php->login(): Login error. exception 'OC_Mail_NetworkingException' with message 'Unable to determine network-status due to technical problems.' in \/var\/www\/html\/owncloud\/apps\/roundcube\/lib\/RoundCubeLogin.class.php:434\nStack trace:\n#0 \/var\/www\/html\/owncloud\/apps\/roundcube\/lib\/RoundCubeLogin.class.php(279): OC_RoundCube_Login->sendRequest('\/mail\/', Array)\n#1 \/var\/www\/html\/owncloud\/apps\/roundcube\/lib\/RoundCubeApp.class.php(357): OC_RoundCube_Login->login('myuser', NULL)\n#2 \/var\/www\/html\/owncloud\/apps\/roundcube\/lib\/RoundCubeAuthHelper.class.php(82): OC_RoundCube_App::login('foo.bar....', '', '\/mail\/', 'myuser', NULL)\n#3 \/var\/www\/html\/owncloud\/apps\/roundcube\/ajax\/adminSettings.php(79): OC_RoundCube_AuthHelper::login(Array)\n#4 \/var\/www\/html\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/html\/o...')\n#5 [internal function]: __lambda_func(Array)\n#6 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(274): call_user_func('?lambda_733', Array)\n#7 \/var\/www\/html\/owncloud\/lib\/base.php(874): OC\\Route\\Router->match('\/apps\/roundcube...')\n#8 \/var\/www\/html\/owncloud\/index.php(40): OC::handleRequest()\n#9 {main}","level":3,"time":"2015-10-09T07:20:34+00:00"}`
```

RoundCube Settings
Absolute path: /mail/
off_ Remove information bar on top of page
on_ Disable SSL verification, e.g. for self-signed certificates
on_ Enable autologin for users
off_ Remove RoundCube header navigation menu items
on_ Enable debug logging

policies "" --> I tried setting another vhost (on the same machine) and got the same errors

Accessing "https://foo.bar.org/mail/" from my browser and from the server itself is working fine.

CentOS7
Owncloud 8.1.3 (stable) 
RoundCube Mail App 2.6.1
roundcubemail-1.1.3-1.el7 rpm from epel7

**Comment by mckaygerhard** [comment]
the decripted pass are not decripted as u see in  `OC_RoundCube_Login->login('myuser', NULL)` this have been reported as #343, if are interesting in solve this please colaborate with coding

note that this app are not developed anymore and if u want a bugfix must also colaborate in fixing, this due constants changes in oc api since oc get a more dinamic life of developing
